appNamespace: "chooseAnUniqueNameForYourApp"
timezone: "Europe/Paris"
doctrine:
    driver: "pdo_mysql"
    host: "localhost"
    user: "db_user"
    password: 'db_pass'
    dbname: "db_name"
    port: null
    unix_socket: null
    path: null
cacheDriver:
    type: null
    host: null
    port: null
security:
    secret: 'change#this#secret#very#important'
mailer:
    type: null
    host: "localhost"
    port: 25
    encryption: false
    username: ''
    password: ''
entities:
    - "../vendor/roadiz/roadiz/src/Roadiz/Core/Entities"
    - "../vendor/roadiz/roadiz/src/Roadiz/Core/AbstractEntities"
    - "gen-src/GeneratedNodeSources"
rememberMeLifetime: 2592000
additionalServiceProviders: []
additionalCommands: []
assetsProcessing:
    driver: gd
    defaultQuality: 90
    maxPixelSize: 1920
    jpegoptimPath: ~
    pngquantPath: ~
    subscribers: []
