#!/bin/bash

set -u
# Source app helpers
source /usr/share/yunohost/helpers

REMOVE_NGINX_CONF () {	# Suppression de la configuration nginx
	if [ -e "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then	# Delete nginx config
		echo "Delete nginx config"
		sudo rm "/etc/nginx/conf.d/$domain.d/$app.conf"
	fi
}

REMOVE_FPM_CONF () {	# Suppression de la configuration du pool php-fpm
	if [ -e "/etc/php5/fpm/pool.d/$app.conf" ]; then	# Delete fpm config
		echo "Delete fpm config"
		sudo rm "/etc/php5/fpm/pool.d/$app.conf"
	fi
}

# retrieve arguments
app=$YNH_APP_INSTANCE_NAME
dbname=$app
dbuser=$app
domain=$(ynh_app_setting_get $app domain)

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname"
ynh_mysql_drop_user "$dbuser"

sudo rm -rf /var/www/$app
REMOVE_NGINX_CONF
REMOVE_FPM_CONF 

sudo service nginx reload
sudo service php5-fpm reload
